language: php

php:
  - '7.4.27'
  - '8.2.0'

addons:
  apt:
    update: true
    packages:
      - libonig-dev

# RabbitMQ requires setuid flags, so you can only run RabbitMQ on standard, OSX or Trusty infrastructure
# (ie, your .travis.yml must contain sudo: required
sudo: false

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpcs --standard=psr2 lib/
  - vendor/bin/phpunit -d zend.enable_gc=0 --coverage-text --coverage-clover=coverage.clover
